#!/usr/bin/env python3
"""Bring gated films into the site and generate app/explainers.ts. Nothing ungated is copied.

- Part explainers (content-ideas runs/2026-10-03-part-explainers/<slug>/out): copied to public/media/explainers/
  only when verify_film.py exits 0 on them now; lengths are read from the file, titles from the storyboard.
- DG32 films with motion (runs/2026-10-03-film-motion-overlay/<id>/out): replace public/media/<id>.mp4 in place
  only when verify_overlay.py exits 0 (audio and captions identical, so the .vtt and poster stay).
Usage: python3 scripts/explainers/sync.py [--dry-run] [--skip-films]
"""
import json, pathlib, shutil, subprocess, sys
HOME = pathlib.Path.home(); SITE = pathlib.Path(__file__).resolve().parents[2]
RUNS = HOME / "content-ideas/runs"; SK = HOME / "content-ideas/skills"
PARTS = ["sku-1", "sku-2", "sku-3", "sku-4", "sku-5", "sku-6", "sku-7", "sku-8", "sku-9", "d100"]
FILMS = ["dg32-lite-architecture", "dg32-2dom-architecture", "dg32-lite-datasheet", "dg32-lite-tapein", "dg32-2dom-datasheet"]
dry = "--dry-run" in sys.argv; skip_films = "--skip-films" in sys.argv

def ok(cmd): return subprocess.run(cmd, capture_output=True, text=True).returncode == 0
def mmss(t): return f"{int(t // 60)}:{int(round(t % 60)):02d}"

rows, out = [], SITE / "public/media/explainers"
if not dry: out.mkdir(parents=True, exist_ok=True)
for s in PARTS:
    run = RUNS / "2026-10-03-part-explainers" / s; name = f"{s}-explainer"
    if not (run / "out" / f"{name}.mp4").exists() or not ok(["python3", str(SK / "part-explainer-film/scripts/verify_film.py"), str(run), "--out", name]):
        print(f"skip {s}: no gated film"); continue
    film = json.load(open(run / "out/film.json")); sb = json.load(open(RUNS / f"2026-10-03-arch-storyboards/{s}.json"))
    voice = json.load(open(run / "voice.json")).get("provider")
    for suf in (".mp4", ".vtt", "-poster.jpg"):
        if not dry: shutil.copy(run / "out" / f"{name}{suf}", out / f"{name}{suf}")
    rows.append((s, sb["headline"], mmss(film["duration"]), voice)); print(f"{s}: {mmss(film['duration'])} ({voice})")
for f in ([] if skip_films else FILMS):
    run = RUNS / "2026-10-03-film-motion-overlay" / f; new = run / "out" / f"{f}.mp4"; site = SITE / "public/media" / f"{f}.mp4"
    if new.exists() and ok(["python3", str(SK / "film-motion-overlay/scripts/verify_overlay.py"), str(run), "--original", str(site), "--new", str(new)]):
        if not dry: shutil.copy(new, site)
        print(f"{f}: motion version in place")
    else: print(f"skip {f}: overlay not gated (or already in place)")
ts = ["// GENERATED by scripts/explainers/sync.py from the gated explainer films. Do not edit; re-run the script.",
      "import { url } from './routes';", "import type { Film } from './dg32-films';", "",
      "export type Explainer = Film & { slug: string; code: string };",
      "const e = (slug: string, title: string, length: string): Explainer => ({",
      "  id: slug + '-explainer', slug, code: slug.toUpperCase(), title, sub: 'The architecture in one narrated walk-through', length,",
      "  src: url('/media/explainers/' + slug + '-explainer.mp4'), poster: url('/media/explainers/' + slug + '-explainer-poster.jpg'),",
      "  vtt: url('/media/explainers/' + slug + '-explainer.vtt'),", "});", "", "export const explainers: Explainer[] = ["]
ts += [f"  e({json.dumps(s)}, {json.dumps(h, ensure_ascii=False)}, {json.dumps(l)})," for s, h, l, _ in rows] + ["];", ""]
if not dry: (SITE / "app/explainers.ts").write_text("\n".join(ts), encoding="utf-8")
print(f"{len(rows)} explainers -> app/explainers.ts")
