"""Turn the story-architect storyboard JSON (one per part) into app/arch-stories.ts, validating the schema,
the length limits and the claim rules. Source folder: content-ideas runs/2026-10-03-arch-storyboards/.

    python3 scripts/sku-diagrams/stories.py <storyboard-dir>
"""
import json, os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
IDS = {'sku-1': 'sku1', 'sku-2': 'sku2', 'sku-3': 'sku3', 'sku-4': 'sku4', 'sku-5': 'sku5', 'sku-6': 'sku6', 'sku-7': 'sku7', 'sku-8': 'sku8', 'sku-9': 'sku9', 'd100': 'd100'}
BANNED = re.compile(r'—|\bmoat\b|\bASP\b|₹|\bcrore\b|market size|best-in-class|MCEME|certified\b(?! )|\bspec\b|annex sheet|story pack', re.I)
MARKS = set('①②③④⑤⑥F')
SECTIONS = ('physics', 'specs', 'questions', 'fit', 'evidence', 'sources', 'close')


def words(s): return len(s.split())


def curly(x):
    """Typographic quotes in visible copy: apostrophes and paired double quotes."""
    if isinstance(x, str):
        x = re.sub(r"(\w)'(\w)", "\\1\u2019\\2", x)
        x = re.sub(r"'", "\u2019", x)
        x = re.sub(r'"([^"]*)"', "\u201c\\1\u201d", x)
        return x
    if isinstance(x, list): return [curly(i) for i in x]
    if isinstance(x, dict): return {k: curly(v) for k, v in x.items()}
    return x


def check(slug, d):
    errs = []
    if len(d['headline']) > 80: errs.append(f'headline {len(d["headline"])} chars')
    if words(d['lead']) > 80: errs.append(f'lead {words(d["lead"])} words')
    if not 4 <= len(d['beats']) <= 8: errs.append(f'{len(d["beats"])} beats')
    for i, b in enumerate(d['beats'], 1):
        if len(b['title']) > 70: errs.append(f'beat {i} title {len(b["title"])} chars')
        if not 20 <= words(b['body']) <= 85: errs.append(f'beat {i} body {words(b["body"])} words')
        bad = [m for m in b['marks'] if m not in MARKS]
        if bad: errs.append(f'beat {i} marks {bad}')
    for field in [d['headline'], d['lead'], d['closing']['title'], d['closing']['body']] + [b['title'] + ' ' + b['body'] for b in d['beats']]:
        m = BANNED.search(field)
        if m: errs.append(f'banned "{m.group(0)}" in: {field[:60]}')
    return errs


def main(src):
    out, problems = {}, {}
    for slug, pid in IDS.items():
        f = os.path.join(src, f'{slug}.json')
        d = json.load(open(f, encoding='utf-8'))
        d['id'] = pid
        e = check(slug, d)
        if e: problems[slug] = e
        out[pid] = {k: d[k] for k in ('id', 'headline', 'lead', 'beats', 'closing')}
        sf = os.path.join(src, f'{slug}.sections.json')
        if os.path.exists(sf):
            sec = json.load(open(sf, encoding='utf-8'))
            out[pid]['sections'] = {k: sec[k] for k in SECTIONS}
            for k in SECTIONS:
                t, c = sec[k]['title'], sec[k]['copy']
                if len(t) > 90: e.append(f'{k} title {len(t)} chars')
                if words(c) > 55: e.append(f'{k} copy {words(c)} words')
                m = BANNED.search(t + ' ' + c)
                if m: e.append(f'banned "{m.group(0)}" in {k}')
            if e: problems[slug] = e
    out = curly(out)
    for s, e in problems.items(): print(s, '->', '; '.join(e))
    if problems: sys.exit(1)
    ts = ('// GENERATED by scripts/sku-diagrams/stories.py from the story-architect storyboards '
          '(content-ideas runs/2026-10-03-arch-storyboards). Edit the storyboard JSON, then regenerate.\n'
          "import type {ArchStory} from './detail';\n\nexport const archStories: Record<string, ArchStory> = "
          + json.dumps(out, ensure_ascii=False, indent=1) + ';\n')
    open(os.path.join(ROOT, 'app/arch-stories.ts'), 'w', encoding='utf-8').write(ts)
    print(f'{len(out)} storyboards -> app/arch-stories.ts')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/content-ideas/runs/2026-10-03-arch-storyboards'))
