'use client';
import {useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {url} from './routes';
import {portfolioParts,stopRules} from './portfolio-story-data';
const functionFor=(p:typeof portfolioParts[number])=>p.id==='sku-7'?'Sensing':p.group==='motion'?'Motion':p.group==='infrastructure'?'Power':p.group==='interfaces'?'Interfaces':'Integration';
export function PortfolioAtlas(){const [job,setJob]=useState('All');return <div className="v6-atlas"><div className="v6-tabs" role="group" aria-label="Filter silicon by function">{['All','Motion','Power','Sensing','Interfaces','Integration'].map(x=><button key={x} aria-pressed={job===x} onClick={()=>setJob(x)}>{x}</button>)}</div><div className="v6-atlas-rows">{portfolioParts.filter(p=>job==='All'||functionFor(p)===job).map(p=><article key={p.id} data-source-node={p.id}><span className="v6-mono">{functionFor(p)}</span><div><h3><a href={url(p.route)}>{p.code} · {p.name} <ArrowUpRight size={16}/></a></h3><p>{p.job}</p><details className="v6-part-detail"><summary>Architecture &amp; boundaries</summary><p>{p.architecture}</p><p className="v6-note">{p.boundary}</p></details></div><div><strong>{p.maturity}</strong><small>Evaluation: {p.evaluation}</small><a href={url(p.source.path)}>{p.source.title} · {p.source.section} ↗</a></div></article>)}</div><p className="v6-note">Nine core SKU architectures plus D100. DG SDV is a separate reference platform. Function groups guide discovery; each source establishes its own scope.</p></div>}
export function EvaluationMatrix(){return <div className="v6-evaluation"><h3>Define what the next evidence must establish.</h3>{portfolioParts.filter(p=>['sku-4','sku-2','sku-3','sku-5','sku-7','track-b-d100'].includes(p.id)).map(p=><article key={p.id}><div><b>{p.code} · {p.name}</b><small>{p.maturity}</small></div><p>{p.evaluation}</p><a href={url(p.source.path)}>Inspect source ↗</a></article>)}</div>}
export function ReuseMap({level=3}:{level?:2|3}={}){const H=(level===2?'h2':'h3') as 'h2'|'h3';return <div className="v6-reuse" aria-label="Shared digital foundation, specialist physical blocks and proposed integration"><div className="v6-foundation"><small>SHARED DIGITAL FOUNDATION</small><H>RISC-V logic · tools · verification</H><p>Reuse implementation methods and digital building blocks across the portfolio.</p></div><div className="v6-specialists">{['Motor power stage','Analog acquisition','Physical interfaces','RF sensing'].map(s=><div key={s}><strong>{s}</strong><span>Specialist physical requirements</span></div>)}</div><div className="v6-proposed"><small>PROPOSED INTEGRATION</small><H>Organic-substrate SiP</H><p>Combine suitable dies and processes in a package. This is a portfolio concept; DG32 uses its own QFN-64 package.</p></div></div>}
export function QualificationRoute(){return <ol className="v6-gates">{[['Design','Architecture, requirements and review records'],['Implementation','RTL verification and physical implementation reports'],['MPW fabrication','Fabrication records and returned silicon'],['Bring-up','Board measurements and functional test results'],['Characterisation','Electrical limits across conditions'],['Qualification','Reliability, safety and application evidence']].map(([a,b],i)=><li key={a}><span className="v6-mono">0{i+1}</span><h3>{a}</h3><p>{b}</p></li>)}</ol>}
export function RoadmapRegister(){return <><div className="v6-roadmaps"><article><span className="v6-mono">PROCESS CHOICES</span><h3>Scale selected logic. Preserve the physical job.</h3><ol className="v6-path"><li><b>130 / 180 nm</b><span>Physical foundation</span></li><li><b>Selective scaling</b><span>Suitable logic blocks</span></li><li><b>28 nm</b><span>Intended compute</span></li></ol><p>Analog, power and RF requirements continue to govern their own blocks.</p></article><article><span className="v6-mono">MANUFACTURING CAPABILITY</span><h3>Build a route to manufacturing resilience.</h3><ol className="v6-path"><li><b>SkyWater 130</b><span>Open process route</span></li><li><b>IHP SG13G2</b><span>Specialist RF route</span></li><li><b>SCL 180</b><span>Intended route</span></li></ol><p>Distinct process and qualification plans, not interchangeable qualified fabs.</p></article></div><div className="v6-stoprules"><h3>Four conditions that change the plan</h3>{stopRules.map((r,i)=><div key={r.id}><span className="v6-mono">{r.id}</span><strong>{r.condition}</strong><p>{r.response}</p></div>)}</div><a className="v6-link" href={url('/downloads/deepgrid-mature-silicon-architecture.md')}>Strategy source · sections 4 and 8 ↗</a></>}
