'use client';
import {url,type RouteId} from './routes';
import './route-journey.css';
type Brief=[string,string,string[],string,string];
const briefs:Partial<Record<RouteId,Brief>>={
products:['From a function to a named part','Portfolio architectures and DG32 variants answer different selection questions.',['Identify the voltage, acquisition or interface job.','DG32 is SKU-4 safety MCU; it is distinct from SKU-1 motor power architecture.','Architecture breadth does not imply production availability.'],'deepgrid-sku-compendium-architecture.md','/applications'],
technology:['Follow the data and the fault','A functional diagram is useful when it explains who acts, what crosses a boundary and what can fail.',['Trace acquired data through ADC, CORDIC, software PI and PWM.','MAIN and CHECKER compare delayed committed results.','2DOM attention crosses a separate clock domain; control remains bounded.'],'dg32-lite-architecture-guide.md','/technology/control-loop'],
safety:['Distinguish detection from the complete response','Two-cycle checker skew and the reported 39-cycle fault response are different quantities.',['Comparator mismatch records a sticky first cause.','FAULT_N must connect to the external driver-disable path.','Reset and injection behaviour require validation; lockstep is not certification.'],'dg32-lite-architecture-guide.md','/evidence'],
control:['Budget the entire loop','The hardware datapath is only part of a current-control iteration.',['ADC acquisition: 177 cycles; CORDIC: 53–58 cycles.','d/q PI regulators run in firmware.','82% diagnostic headroom belongs to 10 kHz operation, not the ≈100 kHz ceiling.'],'dg32-lite-architecture-guide.md','/applications'],
die:['Separate layout evidence from functional geometry','A die view explains physical organisation; an illustrative cutaway cannot establish manufactured silicon.',['Check the implementation record and its revision.','Relate placement and routing to timing, clocks and power.','Post-route estimates need characterisation before becoming measured limits.'],'dg32-lite-architecture-guide.md','/evidence'],
package:['The board sees pins and electrical limits','The QFN-64 interface is where design assumptions become board requirements.',['DG32 package scope: 9 × 9 mm QFN-64.','Check 1.8 V core / 3.3 V I/O requirements against the source.','Pin-map confirmation, thermal behaviour and electrical limits require characterisation.'],'dg32-lite-architecture-guide.md','/contact'],
applications:['Start at the system, then inspect the workload','The indexed playbook maps tasks to signals, rates and implementation limits.',['Separate an application concept from a tested deployment.','A classifier needs usable signal quality, memory and cycle budget.','An advisory diagnosis does not replace the hardware fault path.'],'deepgrid-dg32-ai-architecture.md','/products'],
'uc-motors':['A drive is more than its controller','Motion puts the power stage, feedback, control loop and shutdown path in one engineering decision.',['SKU-1 addresses the motor-drive architecture; DG32 provides checked control.','Specify bus voltage, phase current, sensor topology and loop rate.','Validate driver-disable wiring and coast-down behaviour under a fault.'],'deepgrid-sku-compendium-architecture.md','/technology/safety'],
'uc-vehicles':['A vehicle harness shapes the silicon','Zonal integration depends on local loads, interfaces and system requirements.',['SKU-5 provides the physical interface architecture; SKU-9 the zonal scope.','DG SDV is a reference-platform architecture.','Transients, EMC and vehicle qualification remain application-specific evidence needs.'],'deepgrid-sdv-architecture.md','/products'],
'uc-defence':['Begin with the platform and its qualification route','Drone, avionics and defence use cases do not share one universal requirement.',['D100 supplies the drone architecture context.','State power, communications, environment and flight or mission constraints.','Treat screening, qualification and procurement eligibility as separate decisions.'],'deepgrid-d100-architecture.md','/company'],
'uc-grid':['Measurement quality decides the meter','Metering combines acquisition, calibration, power and deployment economics.',['SKU-2 is the meter architecture; PMIC and supervision are adjacent jobs.','Define accuracy, channels, isolation and calibration conditions.','An unsigned deployment commitment is a reason to delay the programme.'],'deepgrid-sku-compendium-architecture.md','/company'],
'uc-boards':['Predictable startup begins below firmware','Power management, reset supervision and interfaces support nearly every board.',['SKU-3 addresses rails and sequencing; SKU-6 addresses supervision.','Define supply ramp, brownout, reset and recovery requirements.','Check physical-layer voltage and harness constraints for SKU-5.'],'deepgrid-sku-compendium-architecture.md','/contact'],
evidence:['Ask what each result actually proves','Simulation, implementation and laboratory measurements answer different questions.',['Read the claim, method, conditions and revision together.','39 cycles is reported simulated fault response; it is not a measured silicon result.','Architecture and roadmap documents do not establish qualification or availability.'],'dg32-lite-architecture-guide.md','/procurement'],
procurement:['Turn a comparison into an evaluation plan','DG32’s claimed design advantages must be weighed against analog, memory and maturity gaps.',['Check current design requirements against the available source records.','Roadmap features are future scope, not present capability.','Ask for measured evidence before committing a production design.'],'dg32-lite-architecture-guide.md','/contact'],
resources:['Choose a document by the decision it supports','The library spans portfolio strategy, product architecture and workload analysis.',['Use the SKU compendium for function and part scope.','Use DG32 architecture for safety, timing and package details.','Use the AI workload analysis for signals, features and budget limits.'],'deepgrid-sku-compendium-architecture.md','/resources/docs'],
docs:['Read the source behind the figure','A deck or film helps explain; the named specification preserves conditions and caveats.',['Inspect document revision and evidence type.','Keep a latency or headroom figure attached to its operating conditions.','Resolve index shorthand against the corrective claim register and source.'],'dg32-lite-architecture-guide.md','/evidence'],
videos:['Use motion to understand a mechanism','Narrated architecture films illustrate causal paths and domain boundaries.',['A rendered mechanism is an explanation, not a laboratory observation.','Read captions and source documents alongside the animation.','Inspect loop timing and fault response as separate paths.'],'dg32-lite-architecture-guide.md','/technology'],
ask:['Search the index, then verify the source','Indexed retrieval makes the corpus navigable. It cannot independently validate its own assertions.',['Ask for a named product, mechanism or constraint.','Open the citation and check the surrounding conditions.','Treat graph links as discovery; source documents govern publication.'],'deepgrid-sku-compendium-architecture.md','/resources/docs'],
about:['A portfolio organised around physical jobs','The company story should lead to the engineering work and the evidence it needs.',['Motion, power, sensing, interfaces and safety form the portfolio.','Mature processes and reusable digital IP are methods, not proof of economics.','DG32 is the detailed pre-silicon proof point.'],'deepgrid-mature-silicon-architecture.md','/company'],
team:['Match the team to the engineering task','A biography supplies context; product evidence supplies the technical decision.',['Scope architecture, implementation and qualification responsibilities.','Review the source materials before defining an evaluation.','Discuss the system’s constraints with the team.'],'deepgrid-mature-silicon-architecture.md','/contact'],
recognition:['Separate recognition from product readiness','Awards and participation provide company context. They do not prove electrical performance.',['Review the stated programme or achievement in its own scope.','Do not transfer recognition to product certification.','Use the evidence register for design and implementation results.'],'dg32-lite-architecture-guide.md','/evidence'],
contact:['Bring the constraints that decide the part','A useful enquiry starts with a system requirement and a defined evidence gap.',['State the platform and silicon function, not only the chip name.','Include voltage, signal quality, interfaces, timing and environment.','Name qualification requirements and what must be measured before adoption.'],'deepgrid-sku-compendium-architecture.md','/products']};
export function RouteJourney({route}:{route:RouteId}){const b=briefs[route];if(!b)return null;return <aside className="route-journey" aria-label="Engineering evaluation guide"><div><span>YOUR EVALUATION / {route.toUpperCase()}</span><h2>{b[0]}</h2><p>{b[1]}</p></div><ol>{b[2].map((x,i)=><li key={x}><b>0{i+1}</b>{x}</li>)}</ol><nav aria-label="Evaluation next steps"><a href={url('/downloads/'+b[3])}>Read the relevant architecture ↗</a><a href={url(b[4])}>Continue the evaluation ↗</a></nav></aside>}
